import React from 'react';
import { cn } from '../../../utils/classnames';
import { formatName } from '../../../utils';
import { getServicePrimaryColor } from '../../../data/services';
import type { SearchResult } from '../types';

interface SearchResultItemProps {
  result: SearchResult;
  isSelected: boolean;
  onSelect: (result: SearchResult) => void;
  onMouseEnter: () => void;
}

function formatDate(timestamp: string): string {
  const date = new Date(timestamp);
  const month = (date.getMonth() + 1).toString().padStart(2, '0');
  const day = date.getDate().toString().padStart(2, '0');
  return `${date.getFullYear()}/${month}/${day}`;
}

function truncate(text: string, maxLength: number): string {
  if (text.length <= maxLength) return text;
  return text.slice(0, maxLength) + '...';
}

export const SearchResultItem: React.FC<SearchResultItemProps> = ({
  result,
  isSelected,
  onSelect,
  onMouseEnter,
}) => {
  const primaryColor = getServicePrimaryColor(result.service);
  const displayContent = result.snippet ?? (result.content ? truncate(result.content, 100) : '');

  return (
    <div
      className={cn(
        'flex items-center gap-3 px-4 py-2.5 cursor-pointer transition-colors',
        isSelected ? 'bg-blue-50' : 'hover:bg-gray-50'
      )}
      onClick={() => onSelect(result)}
      onMouseEnter={onMouseEnter}
    >
      {/* Service color dot */}
      <div
        className="w-1.5 h-1.5 rounded-full shrink-0"
        style={{ backgroundColor: primaryColor }}
      />

      {/* Main content area */}
      <div className="flex-1 min-w-0">
        <div className="flex items-baseline gap-1.5">
          <span className="font-medium text-sm text-gray-900 truncate">
            {formatName(result.member_name)}
          </span>
          <span className="text-xs text-gray-400 shrink-0">&middot;</span>
          <span className="text-xs text-gray-400 truncate">
            {result.group_name}
          </span>
        </div>
        {displayContent && (
          result.snippet ? (
            // Snippet HTML contains <mark> tags generated by the search backend
            // for keyword highlighting. Content is from our own trusted API.
            <p
              className="text-sm text-gray-500 line-clamp-2 mt-0.5 search-snippet"
              dangerouslySetInnerHTML={{ __html: result.snippet.replace(/\r?\n/g, ' ') }}
            />
          ) : (
            <p className="text-sm text-gray-500 line-clamp-2 mt-0.5">
              {displayContent}
            </p>
          )
        )}
      </div>

      {/* Timestamp */}
      <span className="text-xs text-gray-400 shrink-0 tabular-nums">
        {formatDate(result.timestamp)}
      </span>
    </div>
  );
};
